#!/usr/bin/env python3

import os
import subprocess
import re
import sys
import argparse
from multiprocessing import Pool, cpu_count

# --- Partition Mapping ---
PARTITION_MAPPING = {
    "vendor": ["vendor"],
    "odm": ["odm"],
    "system_ext": ["system_ext"]
}

# --- Helper Functions ---

def find_file_in_aosp(file_name_and_aosp_root):
    """
    Uses mgrep to find if ANY file with the given name exists in AOSP.
    Returns True if found, False otherwise.
    """
    file_name, aosp_root = file_name_and_aosp_root  # Unpack arguments

    # Search using mgrep (case-insensitive)
    mgrep_command = ["mgrep", "-i", "-r", file_name] 
    try:
        mgrep_result = subprocess.run(mgrep_command, capture_output=True, text=True, check=False, cwd=aosp_root)
        if mgrep_result.returncode == 0:
            print(f"Found {file_name} in AOSP using mgrep")
            return True
    except subprocess.CalledProcessError as e:
        print(f"Error running mgrep: {e}")
        return False
    except FileNotFoundError:
        print("Error: mgrep not found. Make sure it is available in your environment.")
        return False

    return False  # File not found

def get_partition_from_path(file_path):
    """
    Infers the partition from the file path (without leading /).
    """
    for partition, path_prefixes in PARTITION_MAPPING.items():
        for prefix in path_prefixes:
            if file_path.startswith(prefix + "/"):
                return partition
    return "unknown"

def process_stock_file(stock_file_and_aosp_root):
    """
    Processes a single stock file.
    """
    stock_file, aosp_root = stock_file_and_aosp_root  # Unpack arguments
    stock_file_name = os.path.basename(stock_file)
    stock_file_partition = get_partition_from_path(stock_file)

    # Apply Exclusions:
    if stock_file_name.endswith((".vdex", ".odex", ".apex", ".wav", ".ogg", ".txt")):
        print(f"  Skipping excluded file type: {stock_file_name}")
        return None

    if stock_file_partition in ["product", "system"]:
        print(f"  Skipping file from product/system partition: {stock_file_name}")
        return None

    # Check if the file exists in AOSP using a broader mgrep search
    if not find_file_in_aosp((stock_file_name, aosp_root)):
        print(f"  {stock_file_name} NOT found in AOSP source.")
        return f"-{stock_file}"
    else:
        print(f"  {stock_file_name} found in AOSP source. Skipping.")
        return None

# --- Main Script ---

def main():
    parser = argparse.ArgumentParser(description="Generate proprietary-files.txt for LineageOS device bringup.")
    parser.add_argument("codename", help="Device codename")
    parser.add_argument("aosp_root", help="Path to AOSP root directory")
    parser.add_argument("-f", "--files", default="all_files.txt", help="Path to the list of all stock firmware files (default: all_files.txt)")
    args = parser.parse_args()

    stock_firmware_files_list = args.files
    device_codename = args.codename
    aosp_root = args.aosp_root
    output_file = "proprietary-files.txt"

    if not os.path.exists(aosp_root) or not os.path.exists(stock_firmware_files_list):
        print("Error: AOSP root directory or all_files.txt does not exist.")
        sys.exit(1)

    # Read the list of all stock firmware files
    try:
        with open(stock_firmware_files_list, 'r') as f:
            stock_files = [line.strip() for line in f]
    except FileNotFoundError:
        print(f"Error: {stock_firmware_files_list} not found.")
        sys.exit(1)

    # Prepare arguments for multiprocessing
    process_args = [(stock_file, aosp_root) for stock_file in stock_files]

    # Parallelize the processing
    num_processes = cpu_count()
    print(f"Using {num_processes} processes...")
    with Pool(processes=num_processes) as pool:
        results = pool.map(process_stock_file, process_args)

    # Filter out None results
    proprietary_files = [r for r in results if r is not None]

    # Write the proprietary-files.txt
    with open(output_file, "w") as f:
        f.write("# This file is generated by a script. Do not modify manually.\n")
        f.write(f"# Device: {device_codename}\n")

        current_partition = ""
        for line in proprietary_files:
            partition = line.split("/")[0].lstrip("-")
            if partition != current_partition:
                f.write(f"\n# {partition}\n")
                current_partition = partition
            f.write(line + "\n")

    print(f"\nGenerated {output_file} for use with extract-files.sh")

if __name__ == "__main__":
    main()