#!/usr/bin/env python3

import os
import subprocess
import re
import sys
import argparse

# --- Partition Mapping ---
PARTITION_MAPPING = {
    "vendor": ["vendor"],
    "odm": ["odm"],
    "system_ext": ["system_ext"],
    "product": ["product"],
    "system": ["system"]
}

# --- Helper Functions ---

def find_module_in_aosp(module_name, aosp_root):
    """
    Uses mgrep and find/egrep to find if a module is defined in AOSP.
    Returns True if found, False otherwise.
    Assumes AOSP source is already synced and environment is set up.
    """

    # Search in Android.mk files using mgrep
    mgrep_command = ["mgrep", "-i", "-r", f"LOCAL_MODULE[[:space:]]*:=[[:space:]]*{module_name}"]
    try:
        mgrep_result = subprocess.run(mgrep_command, capture_output=True, text=True, check=False, cwd=aosp_root)
        if mgrep_result.returncode == 0:
            print(f"Found {module_name} in AOSP using mgrep")
            return True
    except subprocess.CalledProcessError as e:
        print(f"Error running mgrep: {e}")
        return False
    except FileNotFoundError:
        print("Error: mgrep not found. Make sure it is available in your environment.")
        return False

    # Search in Android.bp files using find and egrep
    find_command = [
        "find", aosp_root, "-name", "*.bp", "-print0",
        "|", "xargs", "-0", "egrep", "-i", f"name:[[:space:]]*\"{module_name}\""
    ]
    
    # The output of find is piped to xargs, which in turn constructs and executes the egrep command.
    # xargs is used for better performance for large outputs.
    # we use -print0 in find and -0 in xargs to handle any special characters that might be present in filenames
    try:
        find_result = subprocess.run([' '.join(find_command)], capture_output=True, text=True, check=False, shell=True, cwd=aosp_root)
        if find_result.returncode == 0:
            print(f"Found {module_name} in AOSP using find/egrep")
            return True
    except subprocess.CalledProcessError as e:
        print(f"Error running find/egrep: {e}")
        return False
    except FileNotFoundError:
        print("Error: find or egrep not found. Please ensure they are installed.")
        return False

    return False  # Module not found

def get_partition_from_path(file_path):
    """
    Infers the partition from the file path (without leading /).
    """
    for partition, path_prefixes in PARTITION_MAPPING.items():
        for prefix in path_prefixes:
            if file_path.startswith(prefix + "/"):
                return partition
    return "unknown"

# --- Main Script ---

def main():
    parser = argparse.ArgumentParser(description="Generate proprietary-files.txt for LineageOS device bringup.")
    parser.add_argument("codename", help="Device codename")
    parser.add_argument("aosp_root", help="Path to AOSP root directory")
    parser.add_argument("-f", "--files", default="all_files.txt", help="Path to the list of all stock firmware files (default: all_files.txt)")
    args = parser.parse_args()

    stock_firmware_files_list = args.files
    device_codename = args.codename
    aosp_root = args.aosp_root
    output_file = "proprietary-files.txt"

    if not os.path.exists(aosp_root) or not os.path.exists(stock_firmware_files_list):
        print("Error: AOSP root directory or all_files.txt does not exist.")
        sys.exit(1)

    # 1. Read the list of all stock firmware files (no leading /)
    try:
        with open(stock_firmware_files_list, 'r') as f:
            stock_files = [line.strip() for line in f]
    except FileNotFoundError:
        print(f"Error: {stock_firmware_files_list} not found.")
        sys.exit(1)

    # 2. Iterate through the list and check for corresponding modules in AOSP
    proprietary_files = []
    for stock_file in stock_files:
        stock_file_name = os.path.basename(stock_file)
        stock_file_partition = get_partition_from_path(stock_file)

        # 3. Check if the file exists in AOSP using mgrep/find/egrep
        if not find_module_in_aosp(stock_file_name.removesuffix(".so").removesuffix(".ko"), aosp_root):
            print(f"  {stock_file_name} NOT found in AOSP source.")

            # 4. Format the output for proprietary-files.txt
            if stock_file_partition == "system":
                proprietary_files.append(f"-system/{stock_file}")
            else:
                proprietary_files.append(f"-{stock_file}")
        else:
            print(f"  {stock_file_name} found in AOSP source. Skipping.")

    # 5. Write the proprietary-files.txt
    with open(output_file, "w") as f:
        f.write("# This file is generated by a script. Do not modify manually.\n")
        f.write(f"# Device: {device_codename}\n")

        current_partition = ""
        for line in proprietary_files:
            partition = line.split("/")[0].lstrip("-")
            if partition != current_partition:
                f.write(f"\n# {partition}\n")
                current_partition = partition
            f.write(line + "\n")

    print(f"\nGenerated {output_file} for use with extract-files.sh")

if __name__ == "__main__":
    main()